# Generated by Django 5.2.6 on 2025-09-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cleaner", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cleaner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("company", models.CharField(blank=True, max_length=255)),
                ("vehicle_code", models.CharField(blank=True, max_length=50)),
                ("is_available", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "cleaners",
            },
        ),
    ]
