# Generated by Django 5.2.6 on 2025-09-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("customer_id", models.AutoField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=255)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("address", models.TextField()),
                ("google_location", models.URLField(blank=True)),
                ("building", models.CharField(blank=True, max_length=100)),
                ("unit", models.CharField(blank=True, max_length=50)),
                ("location_notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "customers",
            },
        ),
    ]
