# Generated by Django 5.2.6 on 2025-09-26 08:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"ordering": ["-paid_at"]},
        ),
    ]
