# Generated by Django 5.2.6 on 2025-09-27 14:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0003_alter_payment_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={},
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="amount",
            new_name="booking_amount",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="discount",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="net_amount",
        ),
    ]
