# Generated by Django 5.2.6 on 2025-10-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0004_alter_payment_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="booking_amount",
            new_name="amount",
        ),
        migrations.AddField(
            model_name="payment",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="payment",
            name="net_amount",
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
            preserve_default=False,
        ),
    ]
