# Generated by Django 5.2.6 on 2025-09-22 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("booking", "0001_initial"),
        ("cleaner", "0002_initial"),
        ("customer", "0002_initial"),
        ("service", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_reference", models.CharField(max_length=50, unique=True)),
                ("start_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_date", models.DateField()),
                ("end_time", models.TimeField()),
                ("cleaning_instructions", models.TextField(blank=True)),
                ("special_request", models.TextField(blank=True)),
                ("entry_instruction", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="customer.customer",
                    ),
                ),
            ],
            options={
                "db_table": "bookings",
            },
        ),
        migrations.CreateModel(
            name="BookingCleaner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_cleaners",
                        to="booking.booking",
                    ),
                ),
                (
                    "cleaner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cleaner_bookings",
                        to="cleaner.cleaner",
                    ),
                ),
            ],
            options={
                "db_table": "booking_cleaners",
            },
        ),
        migrations.CreateModel(
            name="BookingService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_of_cleaners", models.PositiveIntegerField(default=1)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_services",
                        to="booking.booking",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_bookings",
                        to="service.service",
                    ),
                ),
            ],
            options={
                "db_table": "booking_services",
            },
        ),
    ]
