# Generated by Django 5.2.6 on 2025-10-02 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0003_remove_bookingservice_number_of_cleaners"),
        ("service", "0004_remove_service_number_of_cleaners_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingservice",
            name="number_of_cleaners",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="bookingservice",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking_services",
                to="service.service",
            ),
        ),
    ]
