# Generated by Django 5.2.6 on 2025-09-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="base_price",
        ),
        migrations.RemoveField(
            model_name="service",
            name="description",
        ),
        migrations.RemoveField(
            model_name="service",
            name="name",
        ),
        migrations.AddField(
            model_name="service",
            name="number_of_cleaners",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="service",
            name="service_type",
            field=models.CharField(
                choices=[("home", "Home Cleaning"), ("office", "Office Cleaning")],
                default=1,
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
