# Generated by Django 5.2.6 on 2025-10-02 03:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "service",
            "0003_remove_service_base_price_remove_service_description_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="number_of_cleaners",
        ),
        migrations.RemoveField(
            model_name="service",
            name="service_type",
        ),
        migrations.AddField(
            model_name="service",
            name="base_price",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="service",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="service",
            name="material",
            field=models.TextField(blank=True, null=True),
        ),
    ]
